### ISSUE TITLE
real_time_factor

### ISSUE THREAD

**Issue by stakaz** [biaslab/RxEnvironments.jl#67]
Hello,

I have a short question: basically, when trying to use your getting started code and setting real_time_factor in for the environment: 

```julia
#...
environment = RxEnvironment(BayesianThermostat(0.0, -10.0, 10.0); emit_every_ms = 900, real_time_factor=5)
#...
```

the temperature still decreases at the same speed in real time. Do I misunderstand the purpose of this argument or is it a bug?

Thanks for a great work ;)

**Comment by wouterwln** [comment]
Hi @stakaz , thanks for trying out `RxEnvironments.jl`! You're absolutely right, I must've overlooked this when coding up the `RxEnvironment` constructor. I'm working on the fix and will have it ready in a couple of minutes
